from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AdminPage(object):
    def setupUi(self, AdminPage):
        AdminPage.setObjectName(_fromUtf8("AdminPage"))
        AdminPage.resize(705, 576)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        AdminPage.setPalette(palette)
        self.centralwidget = QtGui.QWidget(AdminPage)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.declarativeView1 = QtDeclarative.QDeclarativeView(self.centralwidget)
        self.declarativeView1.setGeometry(QtCore.QRect(30, 40, 651, 501))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.declarativeView1.setFont(font)
        self.declarativeView1.setObjectName(_fromUtf8("declarativeView1"))
        self.romnumberinput = QtGui.QPlainTextEdit(self.centralwidget)
        self.romnumberinput.setGeometry(QtCore.QRect(130, 210, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.romnumberinput.setPalette(palette)
        self.romnumberinput.setObjectName(_fromUtf8("romnumberinput"))
        self.roomCSUD = QtGui.QLabel(self.centralwidget)
        self.roomCSUD.setGeometry(QtCore.QRect(50, 50, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.roomCSUD.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.roomCSUD.setFont(font)
        self.roomCSUD.setObjectName(_fromUtf8("roomCSUD"))
        self.roomnumber = QtGui.QLabel(self.centralwidget)
        self.roomnumber.setGeometry(QtCore.QRect(150, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.roomnumber.setFont(font)
        self.roomnumber.setObjectName(_fromUtf8("roomnumber"))
        self.roomtype = QtGui.QLabel(self.centralwidget)
        self.roomtype.setGeometry(QtCore.QRect(150, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName(_fromUtf8("roomtype"))
        self.roomtypeinput = QtGui.QPlainTextEdit(self.centralwidget)
        self.roomtypeinput.setGeometry(QtCore.QRect(130, 290, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.roomtypeinput.setPalette(palette)
        self.roomtypeinput.setObjectName(_fromUtf8("roomtypeinput"))
        self.floor = QtGui.QLabel(self.centralwidget)
        self.floor.setGeometry(QtCore.QRect(400, 180, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.floor.setFont(font)
        self.floor.setObjectName(_fromUtf8("floor"))
        self.floorinput = QtGui.QPlainTextEdit(self.centralwidget)
        self.floorinput.setGeometry(QtCore.QRect(390, 210, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.floorinput.setPalette(palette)
        self.floorinput.setObjectName(_fromUtf8("floorinput"))
        self.roomrateinput = QtGui.QPlainTextEdit(self.centralwidget)
        self.roomrateinput.setGeometry(QtCore.QRect(390, 290, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.roomrateinput.setPalette(palette)
        self.roomrateinput.setObjectName(_fromUtf8("roomrateinput"))
        self.roomrate = QtGui.QLabel(self.centralwidget)
        self.roomrate.setGeometry(QtCore.QRect(400, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.roomrate.setFont(font)
        self.roomrate.setObjectName(_fromUtf8("roomrate"))
        self.tax = QtGui.QLabel(self.centralwidget)
        self.tax.setGeometry(QtCore.QRect(400, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tax.setFont(font)
        self.tax.setObjectName(_fromUtf8("tax"))
        self.taxinput = QtGui.QPlainTextEdit(self.centralwidget)
        self.taxinput.setGeometry(QtCore.QRect(390, 370, 191, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.taxinput.setPalette(palette)
        self.taxinput.setObjectName(_fromUtf8("taxinput"))
        self.availability = QtGui.QLabel(self.centralwidget)
        self.availability.setGeometry(QtCore.QRect(150, 340, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.availability.setFont(font)
        self.availability.setObjectName(_fromUtf8("availability"))
        self.avail = QtGui.QRadioButton(self.centralwidget)
        self.avail.setGeometry(QtCore.QRect(140, 376, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.avail.setFont(font)
        self.avail.setObjectName(_fromUtf8("avail"))
        self.notavail = QtGui.QRadioButton(self.centralwidget)
        self.notavail.setGeometry(QtCore.QRect(230, 376, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.notavail.setFont(font)
        self.notavail.setObjectName(_fromUtf8("notavail"))
        self.createbtn = QtGui.QPushButton(self.centralwidget)
        self.createbtn.setGeometry(QtCore.QRect(140, 460, 91, 41))
        self.createbtn.setObjectName(_fromUtf8("createbtn"))
        self.searchbtn = QtGui.QPushButton(self.centralwidget)
        self.searchbtn.setGeometry(QtCore.QRect(250, 460, 91, 41))
        self.searchbtn.setObjectName(_fromUtf8("searchbtn"))
        self.updatebtn = QtGui.QPushButton(self.centralwidget)
        self.updatebtn.setGeometry(QtCore.QRect(370, 460, 91, 41))
        self.updatebtn.setObjectName(_fromUtf8("updatebtn"))
        self.deletebtn = QtGui.QPushButton(self.centralwidget)
        self.deletebtn.setGeometry(QtCore.QRect(480, 460, 91, 41))
        self.deletebtn.setObjectName(_fromUtf8("deletebtn"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 50, 75, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        AdminPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminPage)
        QtCore.QMetaObject.connectSlotsByName(AdminPage)

    def retranslateUi(self, AdminPage):
        AdminPage.setWindowTitle(_translate("AdminPage", "MainWindow", None))
        self.roomCSUD.setText(_translate("AdminPage", "Iris Hotel CSUD", None))
        self.roomnumber.setText(_translate("AdminPage", "Room Number", None))
        self.roomtype.setText(_translate("AdminPage", "Room Type", None))
        self.floor.setText(_translate("AdminPage", "Floor", None))
        self.roomrate.setText(_translate("AdminPage", "Room Rate", None))
        self.tax.setText(_translate("AdminPage", "Tax", None))
        self.availability.setText(_translate("AdminPage", "Availability", None))
        self.avail.setText(_translate("AdminPage", "Yes", None))
        self.notavail.setText(_translate("AdminPage", "No", None))
        self.createbtn.setText(_translate("AdminPage", "Create", None))
        self.searchbtn.setText(_translate("AdminPage", "Search", None))
        self.updatebtn.setText(_translate("AdminPage", "Update", None))
        self.deletebtn.setText(_translate("AdminPage", "Delete", None))
        self.pushButton.setText(_translate("AdminPage", "Logout", None))

from PyQt4 import QtDeclarative

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    AdminPage = QtGui.QMainWindow()
    ui = Ui_AdminPage()
    ui.setupUi(AdminPage)
    AdminPage.show()
    sys.exit(app.exec_())

