from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReceptionistPage(object):
    def setupUi(self, ReceptionistPage):
        ReceptionistPage.setObjectName(_fromUtf8("ReceptionistPage"))
        ReceptionistPage.resize(705, 578)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        ReceptionistPage.setPalette(palette)
        self.centralwidget = QtGui.QWidget(ReceptionistPage)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 681, 371))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.viewregist = QtWebKit.QWebView(self.tab)
        self.viewregist.setGeometry(QtCore.QRect(0, 0, 681, 351))
        self.viewregist.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.viewregist.setObjectName(_fromUtf8("viewregist"))
        self.nik = QtGui.QLabel(self.tab)
        self.nik.setGeometry(QtCore.QRect(30, 30, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nik.setFont(font)
        self.nik.setObjectName(_fromUtf8("nik"))
        self.nikinput = QtGui.QPlainTextEdit(self.tab)
        self.nikinput.setGeometry(QtCore.QRect(30, 50, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.nikinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nikinput.setFont(font)
        self.nikinput.setObjectName(_fromUtf8("nikinput"))
        self.fullname = QtGui.QLabel(self.tab)
        self.fullname.setGeometry(QtCore.QRect(30, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fullname.setFont(font)
        self.fullname.setObjectName(_fromUtf8("fullname"))
        self.fullnameinput = QtGui.QPlainTextEdit(self.tab)
        self.fullnameinput.setGeometry(QtCore.QRect(30, 110, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fullnameinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fullnameinput.setFont(font)
        self.fullnameinput.setObjectName(_fromUtf8("fullnameinput"))
        self.phonenumber = QtGui.QLabel(self.tab)
        self.phonenumber.setGeometry(QtCore.QRect(30, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phonenumber.setFont(font)
        self.phonenumber.setObjectName(_fromUtf8("phonenumber"))
        self.phonenumberinput = QtGui.QPlainTextEdit(self.tab)
        self.phonenumberinput.setGeometry(QtCore.QRect(30, 170, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.phonenumberinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phonenumberinput.setFont(font)
        self.phonenumberinput.setObjectName(_fromUtf8("phonenumberinput"))
        self.cidate = QtGui.QLabel(self.tab)
        self.cidate.setGeometry(QtCore.QRect(210, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cidate.setFont(font)
        self.cidate.setObjectName(_fromUtf8("cidate"))
        self.cidateinput = QtGui.QDateTimeEdit(self.tab)
        self.cidateinput.setGeometry(QtCore.QRect(210, 50, 131, 22))
        self.cidateinput.setObjectName(_fromUtf8("cidateinput"))
        self.codate = QtGui.QLabel(self.tab)
        self.codate.setGeometry(QtCore.QRect(210, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.codate.setFont(font)
        self.codate.setObjectName(_fromUtf8("codate"))
        self.codateinput = QtGui.QDateTimeEdit(self.tab)
        self.codateinput.setGeometry(QtCore.QRect(210, 110, 131, 22))
        self.codateinput.setObjectName(_fromUtf8("codateinput"))
        self.roomtype = QtGui.QLabel(self.tab)
        self.roomtype.setGeometry(QtCore.QRect(210, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName(_fromUtf8("roomtype"))
        self.roominput = QtGui.QComboBox(self.tab)
        self.roominput.setGeometry(QtCore.QRect(210, 170, 131, 22))
        self.roominput.setObjectName(_fromUtf8("roominput"))
        self.roominput.addItem(_fromUtf8(""))
        self.roominput.addItem(_fromUtf8(""))
        self.roominput.addItem(_fromUtf8(""))
        self.roominput.addItem(_fromUtf8(""))
        self.roominput.addItem(_fromUtf8(""))
        self.roominput.addItem(_fromUtf8(""))
        self.totalguest = QtGui.QLabel(self.tab)
        self.totalguest.setGeometry(QtCore.QRect(370, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalguest.setFont(font)
        self.totalguest.setObjectName(_fromUtf8("totalguest"))
        self.gueststotalinput = QtGui.QSpinBox(self.tab)
        self.gueststotalinput.setGeometry(QtCore.QRect(380, 50, 42, 22))
        self.gueststotalinput.setObjectName(_fromUtf8("gueststotalinput"))
        self.totalnights = QtGui.QLabel(self.tab)
        self.totalnights.setGeometry(QtCore.QRect(370, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalnights.setFont(font)
        self.totalnights.setObjectName(_fromUtf8("totalnights"))
        self.totalnightsinput = QtGui.QSpinBox(self.tab)
        self.totalnightsinput.setGeometry(QtCore.QRect(380, 110, 42, 22))
        self.totalnightsinput.setObjectName(_fromUtf8("totalnightsinput"))
        self.roomnumb = QtGui.QLabel(self.tab)
        self.roomnumb.setGeometry(QtCore.QRect(370, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomnumb.setFont(font)
        self.roomnumb.setObjectName(_fromUtf8("roomnumb"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(370, 170, 69, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(510, 30, 141, 211))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.extrabed = QtGui.QCheckBox(self.groupBox)
        self.extrabed.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.extrabed.setObjectName(_fromUtf8("extrabed"))
        self.babycrib = QtGui.QCheckBox(self.groupBox)
        self.babycrib.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.babycrib.setObjectName(_fromUtf8("babycrib"))
        self.spa = QtGui.QCheckBox(self.groupBox)
        self.spa.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.spa.setObjectName(_fromUtf8("spa"))
        self.roomservice = QtGui.QCheckBox(self.groupBox)
        self.roomservice.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.roomservice.setObjectName(_fromUtf8("roomservice"))
        self.laundry = QtGui.QCheckBox(self.groupBox)
        self.laundry.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.laundry.setObjectName(_fromUtf8("laundry"))
        self.driver = QtGui.QCheckBox(self.groupBox)
        self.driver.setGeometry(QtCore.QRect(10, 120, 70, 17))
        self.driver.setObjectName(_fromUtf8("driver"))
        self.carrental = QtGui.QCheckBox(self.groupBox)
        self.carrental.setGeometry(QtCore.QRect(10, 140, 71, 17))
        self.carrental.setObjectName(_fromUtf8("carrental"))
        self.breakfast = QtGui.QCheckBox(self.groupBox)
        self.breakfast.setGeometry(QtCore.QRect(10, 160, 70, 17))
        self.breakfast.setObjectName(_fromUtf8("breakfast"))
        self.dinner = QtGui.QCheckBox(self.groupBox)
        self.dinner.setGeometry(QtCore.QRect(10, 180, 70, 17))
        self.dinner.setObjectName(_fromUtf8("dinner"))
        self.totalpayment = QtGui.QLabel(self.tab)
        self.totalpayment.setGeometry(QtCore.QRect(30, 290, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalpayment.setFont(font)
        self.totalpayment.setObjectName(_fromUtf8("totalpayment"))
        self.totalpaymenttinput = QtGui.QPlainTextEdit(self.tab)
        self.totalpaymenttinput.setGeometry(QtCore.QRect(140, 290, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.totalpaymenttinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.totalpaymenttinput.setFont(font)
        self.totalpaymenttinput.setObjectName(_fromUtf8("totalpaymenttinput"))
        self.dpinputforregist = QtGui.QPlainTextEdit(self.tab)
        self.dpinputforregist.setGeometry(QtCore.QRect(140, 310, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.dpinputforregist.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpinputforregist.setFont(font)
        self.dpinputforregist.setObjectName(_fromUtf8("dpinputforregist"))
        self.dp = QtGui.QLabel(self.tab)
        self.dp.setGeometry(QtCore.QRect(110, 310, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dp.setFont(font)
        self.dp.setObjectName(_fromUtf8("dp"))
        self.submitbtnregist = QtGui.QPushButton(self.tab)
        self.submitbtnregist.setGeometry(QtCore.QRect(530, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submitbtnregist.setFont(font)
        self.submitbtnregist.setObjectName(_fromUtf8("submitbtnregist"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.viewout = QtWebKit.QWebView(self.tab_2)
        self.viewout.setGeometry(QtCore.QRect(0, 0, 681, 351))
        self.viewout.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.viewout.setObjectName(_fromUtf8("viewout"))
        self.nikout = QtGui.QLabel(self.tab_2)
        self.nikout.setGeometry(QtCore.QRect(30, 30, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nikout.setFont(font)
        self.nikout.setObjectName(_fromUtf8("nikout"))
        self.nikinputout = QtGui.QPlainTextEdit(self.tab_2)
        self.nikinputout.setGeometry(QtCore.QRect(30, 50, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.nikinputout.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nikinputout.setFont(font)
        self.nikinputout.setObjectName(_fromUtf8("nikinputout"))
        self.nokmr = QtGui.QLabel(self.tab_2)
        self.nokmr.setGeometry(QtCore.QRect(200, 30, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nokmr.setFont(font)
        self.nokmr.setObjectName(_fromUtf8("nokmr"))
        self.nokmr_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.nokmr_2.setGeometry(QtCore.QRect(190, 50, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.nokmr_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nokmr_2.setFont(font)
        self.nokmr_2.setObjectName(_fromUtf8("nokmr_2"))
        self.cidate_2 = QtGui.QLabel(self.tab_2)
        self.cidate_2.setGeometry(QtCore.QRect(30, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cidate_2.setFont(font)
        self.cidate_2.setObjectName(_fromUtf8("cidate_2"))
        self.cidate2input = QtGui.QDateTimeEdit(self.tab_2)
        self.cidate2input.setGeometry(QtCore.QRect(30, 110, 194, 22))
        self.cidate2input.setObjectName(_fromUtf8("cidate2input"))
        self.codate_2 = QtGui.QLabel(self.tab_2)
        self.codate_2.setGeometry(QtCore.QRect(30, 150, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.codate_2.setFont(font)
        self.codate_2.setObjectName(_fromUtf8("codate_2"))
        self.codate2input = QtGui.QDateTimeEdit(self.tab_2)
        self.codate2input.setGeometry(QtCore.QRect(30, 170, 194, 22))
        self.codate2input.setObjectName(_fromUtf8("codate2input"))
        self.roomtype_2 = QtGui.QLabel(self.tab_2)
        self.roomtype_2.setGeometry(QtCore.QRect(30, 210, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtype_2.setFont(font)
        self.roomtype_2.setObjectName(_fromUtf8("roomtype_2"))
        self.roomtypeinput = QtGui.QPlainTextEdit(self.tab_2)
        self.roomtypeinput.setGeometry(QtCore.QRect(30, 230, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.roomtypeinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.roomtypeinput.setFont(font)
        self.roomtypeinput.setObjectName(_fromUtf8("roomtypeinput"))
        self.eservice = QtGui.QLabel(self.tab_2)
        self.eservice.setGeometry(QtCore.QRect(30, 270, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eservice.setFont(font)
        self.eservice.setObjectName(_fromUtf8("eservice"))
        self.eserviceinput = QtGui.QPlainTextEdit(self.tab_2)
        self.eserviceinput.setGeometry(QtCore.QRect(30, 290, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.eserviceinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.eserviceinput.setFont(font)
        self.eserviceinput.setObjectName(_fromUtf8("eserviceinput"))
        self.totalpayment_2 = QtGui.QLabel(self.tab_2)
        self.totalpayment_2.setGeometry(QtCore.QRect(380, 170, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalpayment_2.setFont(font)
        self.totalpayment_2.setObjectName(_fromUtf8("totalpayment_2"))
        self.dp_2 = QtGui.QLabel(self.tab_2)
        self.dp_2.setGeometry(QtCore.QRect(460, 190, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dp_2.setFont(font)
        self.dp_2.setObjectName(_fromUtf8("dp_2"))
        self.totalpaymenttinput_2 = QtGui.QPlainTextEdit(self.tab_2)
        self.totalpaymenttinput_2.setGeometry(QtCore.QRect(510, 170, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.totalpaymenttinput_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.totalpaymenttinput_2.setFont(font)
        self.totalpaymenttinput_2.setObjectName(_fromUtf8("totalpaymenttinput_2"))
        self.dpinput = QtGui.QPlainTextEdit(self.tab_2)
        self.dpinput.setGeometry(QtCore.QRect(510, 190, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.dpinput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dpinput.setFont(font)
        self.dpinput.setObjectName(_fromUtf8("dpinput"))
        self.cobtn = QtGui.QPushButton(self.tab_2)
        self.cobtn.setGeometry(QtCore.QRect(530, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cobtn.setFont(font)
        self.cobtn.setObjectName(_fromUtf8("cobtn"))
        self.paymentremaininput = QtGui.QPlainTextEdit(self.tab_2)
        self.paymentremaininput.setGeometry(QtCore.QRect(510, 210, 141, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.paymentremaininput.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.paymentremaininput.setFont(font)
        self.paymentremaininput.setObjectName(_fromUtf8("paymentremaininput"))
        self.paymentremaining = QtGui.QLabel(self.tab_2)
        self.paymentremaining.setGeometry(QtCore.QRect(340, 210, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paymentremaining.setFont(font)
        self.paymentremaining.setObjectName(_fromUtf8("paymentremaining"))
        self.Logoutbtn = QtGui.QPushButton(self.tab_2)
        self.Logoutbtn.setGeometry(QtCore.QRect(590, 10, 75, 23))
        self.Logoutbtn.setObjectName(_fromUtf8("Logoutbtn"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        ReceptionistPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(ReceptionistPage)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ReceptionistPage)

    def retranslateUi(self, ReceptionistPage):
        ReceptionistPage.setWindowTitle(_translate("ReceptionistPage", "MainWindow", None))
        self.nik.setText(_translate("ReceptionistPage", "NIK", None))
        self.fullname.setText(_translate("ReceptionistPage", "Full Name", None))
        self.phonenumber.setText(_translate("ReceptionistPage", "Phone Number", None))
        self.cidate.setText(_translate("ReceptionistPage", "Check In Date", None))
        self.codate.setText(_translate("ReceptionistPage", "Check Out Date", None))
        self.roomtype.setText(_translate("ReceptionistPage", "Room Type", None))
        self.roominput.setItemText(0, _translate("ReceptionistPage", "President Suite", None))
        self.roominput.setItemText(1, _translate("ReceptionistPage", "Suit Room", None))
        self.roominput.setItemText(2, _translate("ReceptionistPage", "Junior Suit Room", None))
        self.roominput.setItemText(3, _translate("ReceptionistPage", "Deluxe Room", None))
        self.roominput.setItemText(4, _translate("ReceptionistPage", "Superior Room", None))
        self.roominput.setItemText(5, _translate("ReceptionistPage", "Standart Room", None))
        self.totalguest.setText(_translate("ReceptionistPage", "Total Guests", None))
        self.totalnights.setText(_translate("ReceptionistPage", "Total Nights", None))
        self.roomnumb.setText(_translate("ReceptionistPage", "Room Number", None))
        self.comboBox.setItemText(0, _translate("ReceptionistPage", "101", None))
        self.comboBox.setItemText(1, _translate("ReceptionistPage", "102", None))
        self.comboBox.setItemText(2, _translate("ReceptionistPage", "103", None))
        self.comboBox.setItemText(3, _translate("ReceptionistPage", "104", None))
        self.comboBox.setItemText(4, _translate("ReceptionistPage", "105", None))
        self.comboBox.setItemText(5, _translate("ReceptionistPage", "106", None))
        self.comboBox.setItemText(6, _translate("ReceptionistPage", "107", None))
        self.comboBox.setItemText(7, _translate("ReceptionistPage", "108", None))
        self.comboBox.setItemText(8, _translate("ReceptionistPage", "109", None))
        self.comboBox.setItemText(9, _translate("ReceptionistPage", "110", None))
        self.comboBox.setItemText(10, _translate("ReceptionistPage", "201", None))
        self.comboBox.setItemText(11, _translate("ReceptionistPage", "202", None))
        self.comboBox.setItemText(12, _translate("ReceptionistPage", "203", None))
        self.comboBox.setItemText(13, _translate("ReceptionistPage", "204", None))
        self.comboBox.setItemText(14, _translate("ReceptionistPage", "205", None))
        self.comboBox.setItemText(15, _translate("ReceptionistPage", "206", None))
        self.comboBox.setItemText(16, _translate("ReceptionistPage", "207", None))
        self.comboBox.setItemText(17, _translate("ReceptionistPage", "208", None))
        self.comboBox.setItemText(18, _translate("ReceptionistPage", "209", None))
        self.comboBox.setItemText(19, _translate("ReceptionistPage", "210", None))
        self.groupBox.setTitle(_translate("ReceptionistPage", "Extras", None))
        self.extrabed.setText(_translate("ReceptionistPage", "Extra Bed", None))
        self.babycrib.setText(_translate("ReceptionistPage", "Baby Crib", None))
        self.spa.setText(_translate("ReceptionistPage", "Spa", None))
        self.roomservice.setText(_translate("ReceptionistPage", "Room Service", None))
        self.laundry.setText(_translate("ReceptionistPage", "Laundry", None))
        self.driver.setText(_translate("ReceptionistPage", "Driver", None))
        self.carrental.setText(_translate("ReceptionistPage", "Car Rental", None))
        self.breakfast.setText(_translate("ReceptionistPage", "Breakfast", None))
        self.dinner.setText(_translate("ReceptionistPage", "Dinner", None))
        self.totalpayment.setText(_translate("ReceptionistPage", "Total Payment", None))
        self.dp.setText(_translate("ReceptionistPage", "DP", None))
        self.submitbtnregist.setText(_translate("ReceptionistPage", "Submit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ReceptionistPage", "Registration", None))
        self.nikout.setText(_translate("ReceptionistPage", "NIK", None))
        self.nokmr.setText(_translate("ReceptionistPage", "Room", None))
        self.cidate_2.setText(_translate("ReceptionistPage", "Check In", None))
        self.codate_2.setText(_translate("ReceptionistPage", "Check Out", None))
        self.roomtype_2.setText(_translate("ReceptionistPage", "Room Type", None))
        self.eservice.setText(_translate("ReceptionistPage", "Extra Service", None))
        self.totalpayment_2.setText(_translate("ReceptionistPage", "Total Payment", None))
        self.dp_2.setText(_translate("ReceptionistPage", "DP", None))
        self.cobtn.setText(_translate("ReceptionistPage", "Checkout", None))
        self.paymentremaining.setText(_translate("ReceptionistPage", "Payment Remaining", None))
        self.Logoutbtn.setText(_translate("ReceptionistPage", "Logout", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ReceptionistPage", "Out", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ReceptionistPage = QtGui.QMainWindow()
    ui = Ui_ReceptionistPage()
    ui.setupUi(ReceptionistPage)
    ReceptionistPage.show()
    sys.exit(app.exec_())

